# Section 1: Array Creation & Properties

## 1. Create Arrays 

In [2]:
import numpy as np

 * 1.1 Create a 1D array of all even numbers between 10 and 30. 

In [13]:
evenArray = np.arange(10,31,2)
print("Even numbers from 10 to 30 is : ",evenArray)

Even numbers from 10 to 30 is :  [10 12 14 16 18 20 22 24 26 28 30]


* Create a 3×3 matrix with values from 0 to 8. 

In [17]:
matrix3_3 = np.random.randint(0, 9,(3, 3))
print("Matrix with 3 x 3 dimenstion is : \n",matrix3_3)

Matrix with 3 x 3 dimenstion is : 
 [[3 7 4]
 [3 3 0]
 [5 2 7]]


* Create a 4×4 identity matrix. 

In [24]:
identityMatrix = np.eye(4)
print("Identity matrix with 4*4 dimension is : \n",identityMatrix)

Identity matrix with 4*4 dimension is : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2. Check Array Properties
  

*  Print shape, size, data type, and number of dimensions of the 3×3 matrix. 

In [33]:
npArray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Shape of the array is : ",npArray.shape)
print("Size of the array is : ",npArray.size)
print("Data type of elements is : ",npArray.dtype)
print("Dimensions of array is : ",npArray.ndim)

Shape of the array is :  (3, 3)
Size of the array is :  9
Data type of elements is :  int64
Dimensions of array is :  2


# Section 2: Indexing, Slicing, and Reshaping 

## 3. Array Indexing and Slicing

* Extract the 2nd column of the 3×3 matrix.     

In [66]:
matrix3_3 = matrix3_3 = np.random.randint(0, 9,(3, 3)) 
matrix2ndColumn = matrix3_3[:3, 1:2]
print("3*3 matrix : \n",matrix3_3 ,"\n")
print("2nd column of matrix : \n",matrix2ndColumn)

3*3 matrix : 
 [[5 5 6]
 [7 5 4]
 [5 3 0]] 

2nd column of matrix : 
 [[5]
 [5]
 [3]]


* Get the first 2 rows using slicing

In [74]:
matrix3_3 = matrix3_3 = np.random.randint(0, 9,(3, 3)) 
print("3*3 matrix : \n",matrix3_3,"\n")
print("First 2 rows : \n",matrix3_3[0:2])

3*3 matrix : 
 [[7 3 5]
 [0 8 0]
 [8 8 4]] 

First 2 rows : 
 [[7 3 5]
 [0 8 0]]


## 4. Reshape an Array 

*  Convert the 1D even number array (from Q1) into a 2D array with 2 rows. 

In [99]:
evenArray = np.arange(0,11,2)
print("Even array is : ",evenArray,"\n")
twoDimensionArray = evenArray.reshape(2,3)
print("Even array converted in 2D array is : \n",twoDimensionArray)

Even array is :  [ 0  2  4  6  8 10] 

Even array converted in 2D array is : 
 [[ 0  2  4]
 [ 6  8 10]]


# Section 3: Operations and Broadcasting 

## 5. Broadcasting Operations

* Add 5 to every element of the 4×4 identity matrix.

In [108]:
identityMatrix = np.eye(5)
sumarray = identityMatrix + 5
print("Identity Matrix after adding 5 :  \n",sumarray)

Identity Matrix after adding 5 :  
 [[6. 5. 5. 5. 5.]
 [5. 6. 5. 5. 5.]
 [5. 5. 6. 5. 5.]
 [5. 5. 5. 6. 5.]
 [5. 5. 5. 5. 6.]]


* Multiply every row of a 3×3 array A by [1, 2, 3]. 

multiplyArray = np.array([1, 2, 3])
npArray = np.ones((3,3))

answer = npArray * multiplyArray
print("Array After multiplying with [1,2,3] is : \n",answer)

# 6. Element-wise Operations 

## 7. Statistics 

* Create a random array of shape (5, 4) with values from a normal distribution.

* Compute mean and standard deviation along axis 0 and 1. 

randomArray = np.random.randint(0,11,(5,4))

print("Array with random numbers with 5*4 shape: ",randomArray,"\n")

print("Mean from Array with axis-0 is : ",randomArray.mean(axis=0))
print("Mean from Array with axis-1 is : ",randomArray.mean(axis=1),"\n")

print("Standard Daviation from Array with axis-0 is : ",randomArray.std(axis=0))
print("Standard Daviation from Array with axis-1 is : ",randomArray.std(axis=1))

## 8. Boolean Masking

 * From the array in Q7, extract all elements greater than the overall mean.

In [6]:
arr = np.array([10, 20, 30, 40, 50])
mean = arr.mean()
print("Array is : ",arr)
print("Mean is  : ",mean)
result = arr[arr > mean]
print("Elements greater than means are : ",result)

Array is :  [10 20 30 40 50]
Mean is  :  30.0
Elements greater than means are :  [40 50]


# Section 5: Linear Algebra 

## 9. Matrix Multiplication 

* Create two compatible matrices and perform matrix multiplication 

In [17]:
matrix1 = np.random.randint(0,11,(3,3))
matrix2 = np.random.randint(0,11,(3,3)) 
print(matrix1)
print(matrix2)

[[0 4 7]
 [7 5 5]
 [2 3 0]]
[[7 6 2]
 [0 3 1]
 [0 1 3]]
[[ 0 24 14]
 [ 0 15  5]
 [ 0  3  0]]
