## Practical No.2: Write a NumPy program to implement following operation 

In [2]:
import numpy as np

* to convert a list of numeric values into a one-dimensional NumPy array 

In [22]:
numericList = [1,2,3,4,5]
listToArray = np.array(l)
print("Original list : ",numericList)
print("Converted list from one-dimensional array : ",listToArray)

Original list :  [1, 2, 3, 4, 5]
Converted list from one-dimensional array :  [1 2 3 4 5]


* to create a 3x3 matrix with values ranging from 2 to 10 

In [4]:
generateNums = np.arange(2, 11)
# print(generateNums)
matrixedArray= generateNums.reshape(3,3)
print("generated 3*3 matrix is : \n", matrixedArray)

generated 3*3 matrix is : 
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


* to append values at the end of an array 

In [35]:
appendArray=np.append(generateNums,[12,13])
print("Array after appending 12 and 13 : ",appendArray)

Array after appending 12 and 13 :  [ 2  3  4  5  6  7  8  9 10 12 13]


* to create another shape from an array without changing its data (3 * 2 to 2 * 3)

In [66]:
generateArray = np.arange(0,6)
Array3_2 = generateArray.reshape(3,2)
print("Array with shape",Array3_2.shape,":\n",Array3_2,"\n")
Array2_3 = Array3_2.reshape(2,3)
print("Array with shape",Array2_3.shape,":\n",Array2_3)

Array with shape (3, 2) :
 [[0 1]
 [2 3]
 [4 5]] 

Array with shape (2, 3) :
 [[0 1 2]
 [3 4 5]]
