## Practical No.3: Write a NumPy program to implement following operation 

In [1]:
import numpy as np

* to split an array of 14 elements into 3 arrays, each with 2, 4, and 8 elements in the 
original order

In [14]:
mainArray = np.arange(0,14)
split2 = mainArray[:2]
split4 = mainArray[2:6]
split8 = mainArray[6:]
print("Main Array : ",mainArray)
print("Array with 2 elements : ",split2)
print("Array with 4 elements : ",split4)
print("Array with 4 elements : ",split8)


Main Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
Array with 2 elements :  [0 1]
Array with 4 elements :  [2 3 4 5]
Array with 4 elements :  [ 6  7  8  9 10 11 12 13]


* to stack arrays horizontally (column wise) 

In [22]:
firstArray = np.array([[1,2,3],[3,2,1]])
secondArray = np.array([[4,5,6],[6,5,4]])
stackedArray = np.hstack([firstArray,secondArray])
print("First Array : \n",firstArray)
print("Second Array : \n",secondArray)
print("Both Arrays after stacked horizontally (column wise) : \n",stackedArray)

First Array : 
 [[1 2 3]
 [3 2 1]]
Second Array : 
 [[4 5 6]
 [6 5 4]]
Both Arrays after stacked horizontally (column wise) : 
 [[1 2 3 4 5 6]
 [3 2 1 6 5 4]]
